name: New Module
description: File a new module issue
title: "<Module Title>"
labels: ["module"]
body:
  - type: markdown
    attributes:
      value: Provide a general summary of the module in the Title above.

  - type: dropdown
    id: provider
    attributes:
      label: For which Cloud provider do you need the module?
      options:
        - Microsoft Azure
        - Google Cloud
        - Amazon Web Services (AWS)
        - Alibaba Cloud
        - Hetzner Cloud
      default: 0
    validations:
      required: true

  - type: textarea
    id: general-information
    attributes:
      label: General Information
      description: |
        Add general information about the module here.
        (Short description, Use-cases, links to related issues, etc.)
      value: |
        ## General Information

    validations:
      required: true