direction: right

main

fix: {
  style.multiple: true
}

feature: {
  style.multiple: true
}

breaking-change: {
  style.multiple: true
}

v1337: {
  label: v1.33.7
  shape: package
  style.fill: lightgreen
}

v1320-rc5: {
  label: v1.33.0-rc5
  shape: package
  style.fill: orange
}

fix -> main: merged as PR
feature -> main: merged as PR
breaking-change -> main: merged as PR

main -> v1320-rc5: auro-release via Actions

main -> release/v1: manual merge\non release day

release/v1 -> v1337
