name: module-github-project

on:
  workflow_call:

jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudeteer/actions/manage-github-project@main
        with:
          project-url: https://github.com/orgs/cloudeteer/projects/37
          app-id: ${{ vars.ORGA_GITHUB_APP_ID_CDTGITHUBPROJECTMANAGEMENT }}
          private-key: ${{ secrets.ORGA_GITHUB_APP_SECRET_CDTGITHUBPROJECTMANAGEMENT }}
