name: module-ci-validate
on: workflow_call
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@42-use-a-specific-terraform-version-during-githubu-actions
        with:
          file-path: versions.tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform_version.outputs.required_version }}

      - name: terraform init
        run: terraform init -backend=false

      - name: terraform fmt
        run: terraform fmt -check -recursive -diff -write=false

      - name: terraform validate
        run: terraform validate
