name: module-ci-lint
on: workflow_call
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - name: Get terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform_version.outputs.required_version }}

      - name: Checkout tflint.hcl
        uses: actions/checkout@v4
        with:
          path: .terraform-governance
          repository: cloudeteer/terraform-governance
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            tflint.hcl
            tflint.examples.hcl
            tflint.tests.hcl

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Show version
        run: tflint --version

      - name: Compare TFLint configuration files
        continue-on-error: true
        run: |
          diff -u .terraform-governance/tflint.hcl .tflint.hcl
          result=$?

          if [ $result -eq 1 ]; then
            echo "::warning::Your local .tflint.hcl file is different from the default one in the cloudeteer/terraform-governance repository. Please update your configuration file accordingly to make sure you have consistent documentation results."
          elif [ $result -ge 1 ]; then
            exit $result
          fi

          diff -u .terraform-governance/tflint.examples.hcl .tflint.examples.hcl
          result=$?

          if [ $result -eq 1 ]; then
            echo "::warning::Your local .tflint.examples.hcl file is different from the default one in the cloudeteer/terraform-governance repository. Please update your configuration file accordingly to make sure you have consistent documentation results."
          elif [ $result -ge 1 ]; then
            exit $result
          fi

      - name: Init TFLint
        run: tflint --init --config=.terraform-governance/tflint.hcl
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: |
          tflint --recursive --chdir=examples --config=$(pwd)/.terraform-governance/tflint.examples.hcl --format=compact
          tflint --config=$(pwd)/.terraform-governance/tflint.hcl --format=compact
