name: module-ci-validate
on: workflow_call
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Format
        run: |
          terraform fmt -check -recursive -diff -write=false

      - name: Validate Code
        run: |
          terraform init -backend=false
          terraform validate
