name: module-ci

on:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
      ARM_SUBSCRIPTION_ID:
      ARM_TENANT_ID:

jobs:
  validate:
    uses: ./.github/workflows/module-ci-validate.yaml

  lint:
    uses: ./.github/workflows/module-ci-lint.yaml

  documentation:
    uses: ./.github/workflows/module-ci-documentation.yaml

  code-analysis:
    uses: ./.github/workflows/module-ci-code-analysis.yaml

  test:
    uses: ./.github/workflows/module-ci-test.yaml
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  issue:
    if: github.event_name == 'schedule' && failure()
    needs: [validate, lint, documentation, code-analysis, test]
    uses: ./.github/workflows/module-ci-issue.yaml
