name: module-github-pull-request
on: workflow_call

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: mheap/github-action-required-labels@8afbe8ae6ab7647d0c9f0cfa7c2f939650d22509 # v5
        with:
          mode: exactly
          count: 1
          labels: "breaking-change,feature,fix,other,ignore-release"
