name: module-ci-documentation
on: workflow_call
jobs:
  documentation:
    runs-on: ubuntu-latest
    container:
      image: quay.io/terraform-docs/terraform-docs:0.19.0
    steps:
      - name: Install prerequisites
        run: apk add git

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Checkout terraform-docs.yaml
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: .terraform-governance
          repository: cloudeteer/terraform-governance
          sparse-checkout-cone-mode: false
          sparse-checkout: config/terraform-docs.yaml

      - name: Compare terraform-docs configuration files
        continue-on-error: true
        run: |
          if diff -u .terraform-governance/config/terraform-docs.yaml .terraform-docs.yaml > /dev/null; then
            echo "No differences found in terraform-docs.yaml"
          else
            result=$?
            if [ $result -eq 1 ]; then
            echo "::warning::Your local .terraform-docs.yaml file is different from the default one in the cloudeteer/terraform-governance repository. Please update your configuration file accordingly to make sure you have consistent documentation results."
            elif [ $result -gt 1 ]; then
              echo "::error::An error occurred while comparing .terraform-docs.yaml files."
            fi
          fi

      - name: Check for diff in terraform-docs
        run: terraform-docs . --config .terraform-governance/config/terraform-docs.yaml --output-check
