name: module-ci-code-analysis
on: workflow_call

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Misconfiguration & Secret Scanner
        uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37 # 0.31.0
        with:
          exit-code: "1"
          ignore-unfixed: true
          scan-type: fs
          scanners: config,secret
          severity: CRITICAL,HIGH
          skip-dirs: examples/,tests/
