name: module-ci-validate
on: workflow_call
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: ${{ steps.terraform_version.outputs.required_version }}

      - name: terraform init
        run: terraform init -backend=false

      - name: terraform fmt
        run: terraform fmt -check -recursive -diff -write=false

      - name: terraform validate
        run: terraform validate
