name: module-github

on:
  workflow_call:
    inputs:
      run_job_project:
        description: 'run project job'
        default: true
        type: boolean

jobs:
  project:
    if: inputs.run_job_project && (github.event_name == 'pull_request' || github.event_name == 'issues')
    uses: ./.github/workflows/module-github-project.yaml
    secrets: inherit
  pull-request:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/module-github-pull-request.yaml
  release:
    # If the push event triggering this workflow is the first commit on a branch,
    # `github.event.before` will always be "0000000000000000000000000000000000000000".
    # With this knowledge, we can skip the release process on the initial commit,
    # which is handled by CI during repository bootstrapping.
    if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch && github.event.before != '0000000000000000000000000000000000000000'
    uses: ./.github/workflows/module-github-release.yaml
