name: module-ci-test

on:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
      ARM_SUBSCRIPTION_ID:
      ARM_TENANT_ID:

jobs:
  test-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Get terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@main
        with:
          directory: tests/remote

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ steps.terraform_version.outputs.required_version }}

      - name: terraform test examples
        run: |
          terraform init -test-directory=tests/examples
          terraform test -test-directory=tests/examples

  test-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Get terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@main
        with:
          directory: tests/remote

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ steps.terraform_version.outputs.required_version }}

      - name: terraform test local
        run: |
          terraform init -test-directory=tests/local
          terraform test -test-directory=tests/local

  test-remote:
    # This workflow is configured to run remote tests only on pull requests.
    # The Azure Managed Identity Federation configuration restricts authentication to the 'pull_request' event type.
    # Additionally, remote tests are skipped for draft pull requests.
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Get terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@main
        with:
          directory: tests/remote

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ steps.terraform_version.outputs.required_version }}

      - name: az login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: terraform test remote
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: |
          terraform init -test-directory=tests/remote
          terraform test -test-directory=tests/remote
