name: module-ci

on:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
      ARM_SUBSCRIPTION_ID:
      ARM_TENANT_ID:

jobs:
  validate:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'labeled')
    uses: ./.github/workflows/module-ci-validate.yaml

  lint:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'labeled')
    uses: ./.github/workflows/module-ci-lint.yaml

  documentation:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'labeled')
    uses: ./.github/workflows/module-ci-documentation.yaml

  code-analysis:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'labeled')
    uses: ./.github/workflows/module-ci-code-analysis.yaml

  test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'labeled')
    uses: ./.github/workflows/module-ci-test.yaml
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  pull-request:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/module-ci-pull-request.yaml

  release:
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs: [validate, lint, documentation, code-analysis, test]
    uses: ./.github/workflows/module-ci-release.yaml

  issue:
    if: github.event_name == 'schedule' && failure()
    needs: [validate, lint, documentation, code-analysis, test]
    uses: ./.github/workflows/module-ci-issue.yaml
