name: module-ci-lint
on: workflow_call
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - name: Get terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@42-use-a-specific-terraform-version-during-githubu-actions

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform_version.outputs.required_version }}

      - name: Checkout tflint.hcl
        uses: actions/checkout@v4
        with:
          path: .terraform-governance
          repository: cloudeteer/terraform-governance
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            tflint.hcl
            tflint.examples.hcl
            tflint.tests.hcl

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init --config=.terraform-governance/tflint.hcl
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: |
          tflint --recursive --chdir=examples --config=$(pwd)/.terraform-governance/tflint.examples.hcl --format=compact
          tflint --config=$(pwd)/.terraform-governance/tflint.hcl --format=compact
