name: module-ci-lint
on: workflow_call
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        name: Checkout source code

      - name: Get terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: ${{ steps.terraform_version.outputs.required_version }}

      - name: Checkout TFLint config files from terraform-governance repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: .terraform-governance
          repository: cloudeteer/terraform-governance
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            config/tflint.hcl
            config/tflint.examples.hcl
            config/tflint.tests.hcl

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4

      - name: Show version
        run: tflint --version

      - name: Compare TFLint configuration files
        continue-on-error: true
        run: |
          ls -al ./
          ls -al .terraform-governance/

          # Compare tflint.hcl
          if diff -u .terraform-governance/config/tflint.hcl .tflint.hcl > /dev/null; then
            echo "No differences found in tflint.hcl"
          else
            result=$?
            if [ $result -eq 1 ]; then
              echo "::warning::Your local .tflint.hcl file is different from the default one in the cloudeteer/terraform-governance repository. Please update your configuration file accordingly to make sure you have consistent documentation results."
            elif [ $result -gt 1 ]; then
              echo "::error::An error occurred while comparing .tflint.hcl files."
            fi
          fi

          # Compare tflint.examples.hcl
          if diff -u .terraform-governance/config/tflint.examples.hcl .tflint.examples.hcl > /dev/null; then
            echo "No differences found in tflint.examples.hcl"
          else
            result=$?
            if [ $result -eq 1 ]; then
              echo "::warning::Your local .tflint.examples.hcl file is different from the default one in the cloudeteer/terraform-governance repository. Please update your configuration file accordingly to make sure you have consistent documentation results."
            elif [ $result -gt 1 ]; then
              echo "::error::An error occurred while comparing .tflint.examples.hcl files."
            fi
          fi

          # Compare tflint.examples.hcl
          if diff -u .terraform-governance/config/tflint.tests.hcl .tflint.tests.hcl > /dev/null; then
            echo "No differences found in tflint.tests.hcl"
          else
            result=$?
            if [ $result -eq 1 ]; then
              echo "::warning::Your local .tflint.tests.hcl file is different from the default one in the cloudeteer/terraform-governance repository. Please update your configuration file accordingly to make sure you have consistent documentation results."
            elif [ $result -gt 1 ]; then
              echo "::error::An error occurred while comparing .tflint.tests.hcl files."
            fi
          fi

      - name: Init TFLint
        run: tflint --init --config=.terraform-governance/config/tflint.hcl
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: |
          tflint --recursive --chdir=examples --config=$(pwd)/.terraform-governance/config/tflint.examples.hcl --format=compact
          tflint --config=$(pwd)/.terraform-governance/config/tflint.hcl --format=compact
